services:

  hexaly:
    build:
      context: ./hexaly_installation
    container_name: hexaly_installation
    volumes:
      - hexaly_data:/opt/hexaly_14_0

  optimization_api_fastapi: # The web server
    build: .
    container_name: optimization_api_fastapi
    ports: # exposing the API on port 80. Change this if you want to use a different port.
      - "8080:80"
    depends_on: # Ensuring that the web server starts after the database.
      - optimization_api_redis
      - optimization_api_postgres
      - hexaly
    volumes:
      - hexaly_data:/opt/hexaly_14_0
    command: python3 -m uvicorn api_main:app --host 0.0.0.0 --port 80 --reload
    environment:
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@optimization_api_postgres:5432/${POSTGRES_DB}

  optimization_api_redis: # The database. We use the official Redis image.
    image: redis:latest
    container_name: optimization_api_redis

  optimization_api_worker: # The worker
    build: .
    command: # Running this command will make our container a worker instead of a web server.
      rq worker --with-scheduler --url redis://optimization_api_redis:6379/1
    depends_on: # Ensuring that the worker starts after the database, as it needs to connect to it.
      - optimization_api_redis
    extra_hosts:
      - "host.docker.internal:host-gateway"
    deploy:
      replicas: 2 # Adding two workers for parallel processing
    volumes:
      - ~/gurobi.lic:/licenses/gurobi.lic:ro
    environment:
      GRB_LICENSE_FILE: /licenses/gurobi.lic
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@optimization_api_postgres:5432/${POSTGRES_DB}

  optimization_api_postgres:
    image: postgres:16
    container_name: optimization_api_postgres
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data


volumes:
  hexaly_data:
  postgres_data: